// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/failover/failover.go.tmpl

// Package failover provides helpers for OTLP exporter endpoint failover.
package failover

import (
	"context"
	"errors"
	"net"
	"net/url"
	"strings"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// IsHTTPTransportError reports whether err represents a transport-level failure
// from an HTTP export attempt. HTTP response errors are not transport errors.
func IsHTTPTransportError(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return false
	}
	msg := err.Error()
	if strings.Contains(msg, "failed to send to") || strings.Contains(msg, "body:") {
		return false
	}
	for e := err; e != nil; e = errors.Unwrap(e) {
		var urlErr *url.Error
		if errors.As(e, &urlErr) {
			return true
		}
		var netErr net.Error
		if errors.As(e, &netErr) {
			return true
		}
	}
	return false
}

// IsGRPCTransportError reports whether err represents a transport-level failure
// from a gRPC export attempt.
func IsGRPCTransportError(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return false
	}
	switch status.Code(err) {
	case codes.Unavailable,
		codes.Aborted,
		codes.OutOfRange,
		codes.DataLoss,
		codes.DeadlineExceeded:
		return true
	default:
		return false
	}
}
