// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/failover/failover_test.go.tmpl

package failover

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/url"
	"testing"

	"github.com/stretchr/testify/assert"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func TestIsHTTPTransportError(t *testing.T) {
	tests := []struct {
		name string
		err  error
		want bool
	}{
		{name: "nil", err: nil, want: false},
		{name: "context canceled", err: context.Canceled, want: false},
		{name: "url error", err: &url.Error{Op: "Post", URL: "http://localhost", Err: errors.New("connection refused")}, want: true},
		{name: "net error", err: &net.DNSError{Err: "no such host", Name: "localhost"}, want: true},
		{name: "http response error", err: fmt.Errorf("failed to send to http://localhost: Bad Request (body: invalid)"), want: false},
		{name: "wrapped url error", err: fmt.Errorf("max retry time elapsed: %w", &url.Error{Op: "Post", URL: "http://localhost", Err: errors.New("timeout")}), want: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, IsHTTPTransportError(tt.err))
		})
	}
}

func TestIsGRPCTransportError(t *testing.T) {
	tests := []struct {
		name string
		err  error
		want bool
	}{
		{name: "nil", err: nil, want: false},
		{name: "context canceled", err: context.Canceled, want: false},
		{name: "unavailable", err: status.Error(codes.Unavailable, "down"), want: true},
		{name: "invalid argument", err: status.Error(codes.InvalidArgument, "bad"), want: false},
		{name: "ok", err: status.Error(codes.OK, ""), want: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, IsGRPCTransportError(tt.err))
		})
	}
}
